"""empty message

Revision ID: 211a19f5523a
Revises: 0f597c218a5b
Create Date: 2025-02-03 15:44:11.039648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211a19f5523a'
down_revision = '0f597c218a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('cost')

    op.drop_table('additional_assets')
    # ### end Alembic commands ###
