"""empty message

Revision ID: c70203bf0f80
Revises: 88e0debec0fd
Create Date: 2025-02-03 12:36:59.372040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c70203bf0f80'
down_revision = '88e0debec0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_request')
    with op.batch_alter_table('intangible_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_cost', sa.Float(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('intangible_assets', schema=None) as batch_op:
        batch_op.drop_column('subscription_cost')

    op.create_table('asset_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('requested_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name='asset_request_approved_by_fkey'),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], name='asset_request_requested_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='asset_request_pkey')
    )
    # ### end Alembic commands ###
